name = "renus"
env = "local"
debug = True
auto_add_translate = True
key = "dfhfUGFKgk@glJKKskkefo648l964kcvnknfjlkd68#49ldfxkcnvkmxcv56738"
public_folder = "public"
ipHeader = "ar-real-ip"
cors_allow = ["*"]
cacheDriver='file'
