import { createApp } from "vue";
import App from "./Index.vue";
import Axios from "./plugins/axios";
import "./registerServiceWorker";
import router from "./router/index";
import renusify from "renusify";

import {
  rApp,
  rContent,
  rMeta,
  rContainer,
  rRow,
  rCol,
  rSpacer,
  rDivider,
  rFileInput,
  rBtn,
  rIcon,
  rCard,
  rModal,
  rTextInput,
  rTelInput,
  rSwitchInput,
  rTableCrud,
  rMessage,
  rTimeAgo,
  rImg,
  rTextArea,
  rAddressInput,
  rCheckInput,
  rPasswprdInput,
  rUniqueInput,
  rSelectInput,
  rBreadcrumbs,
  rNumberInput,
  rRatingInput,
  rTextEditorPreview,
  rAvatar,
  rToolbar,
  rCountDown,
  rSwiper,
  rInfinitePage,
  rInfiniteBox,
  rTimeline,
  rMenu,
  rCheckboxInput,
  rBtnConfirm,
  rMaskInput,
} from "renusify/components";
import { title } from "renusify/directive";
window.app = createApp(App)
  .use(router)
  .use(Axios)
  .use(renusify, {
    rtl: false,
    lang: "en",
    package: "index",
    components:{
      rApp,
      rContent,
      rMeta,
      rContainer,
      rRow,
      rCol,
      rSpacer,
      rDivider,
      rFileInput,
      rBtn,
      rIcon,
      rCard,
      rModal,
      rTextInput,
      rTelInput,
      rSwitchInput,
      rTableCrud,
      rMessage,
      rTimeAgo,
      rImg,
      rTextArea,
      rAddressInput,
      rCheckInput,
      rPasswprdInput,
      rUniqueInput,
      rSelectInput,
      rBreadcrumbs,
      rNumberInput,
      rRatingInput,
      rTextEditorPreview,
      rAvatar,
      rToolbar,
      rCountDown,
      rSwiper,
      rInfinitePage,
      rInfiniteBox,
      rTimeline,
      rMenu,
      rCheckboxInput,
      rBtnConfirm,
      rMaskInput,
    },
    directives: {title},
  })
  .mount("#app");
